= Demo for DPoP Resource Provider

== What to see here

This uses https://github.com/OpenIDC/mod_auth_openidc[nimbus SDK] in a https://quarkus.io[Quarkus] demo application.

== Prerequisites

* Start Keycloak
* Start the SPA
* Java 21

== Starting the demo

. Run the following command to build and start the server:
+
[source,shell script]
----
./mvnw quarkus:dev
----

== Packaging and running the application

The application can be packaged using:

[source,shell script]
----
./mvnw package
----

It produces the `quarkus-run.jar` file in the `target/quarkus-app/` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `target/quarkus-app/lib/` directory.

The application is now runnable using `java -jar target/quarkus-app/quarkus-run.jar`.

If you want to build an _über-jar_, execute the following command:

[source,shell script]
----
./mvnw package -Dquarkus.package.jar.type=uber-jar
----

The application, packaged as an _über-jar_, is now runnable using `java -jar target/*-runner.jar`.

== Related Guides

REST https://quarkus.io/guides/rest[guide]:: A Jakarta REST implementation utilizing build time processing and Vert.x. This extension is not compatible with the quarkus-resteasy extension, or any of the extensions that depend on it.

