quarkus.http.port=9090
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET
quarkus.http.cors.headers=DPoP,Authorization,User-Agent
quarkus.http.cors.exposed-headers=DPoP-Nonce,WWW-Authenticate